In [1]:
import numpy as np
x = np.array([-1, 2, -3, 4])
y = np.abs(x)
print(y)


[1 2 3 4]


In [2]:
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])
z = np.add(x, y)
print(z)


[11 22 33 44]


In [3]:
import numpy as np
x = np.array([0, 1, 2, 3])
y = np.exp(x)
print(y)


[ 1.          2.71828183  7.3890561  20.08553692]


In [4]:
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])
z = np.maximum(x, y)
print(z)


[4 3 3 4]


In [5]:
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])
z = np.minimum(x, y)
print(z)


[1 2 2 1]


In [6]:
import numpy as np
x = np.array([0, np.pi/2, np.pi])
y = np.sin(x)
print(y)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [7]:
import numpy as np
x = np.array([0, np.pi/2, np.pi])
y = np.cos(x)
print(y)


[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [8]:
import numpy as np
x = np.array([0, np.pi/4, np.pi/2])
y = np.tan(x)
print(y)


[0.00000000e+00 1.00000000e+00 1.63312394e+16]


In [9]:
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.log(x)
print(y)


[0.         0.69314718 1.09861229 1.38629436]


In [10]:
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.square(x)
print(y)


[ 1  4  9 16]
